//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.33440
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Broobu.SweNet.Adapter.SweNet {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://esa-spaceweather.net/swenet/xfire-webservice", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ISwenetDataSet", Namespace="http://webservice.http.swenet.estec.esa.eu")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Broobu.SweNet.Adapter.SweNet.ArrayOfString))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Broobu.SweNet.Adapter.SweNet.ArrayOfArrayOfAnyType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Broobu.SweNet.Adapter.SweNet.ArrayOfAnyType))]
    public partial class ISwenetDataSet : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int columnCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Broobu.SweNet.Adapter.SweNet.ArrayOfString columnNamesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Broobu.SweNet.Adapter.SweNet.ArrayOfString columnTypesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Broobu.SweNet.Adapter.SweNet.ArrayOfArrayOfAnyType dataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime endDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int rowCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime startDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tableNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int columnCount {
            get {
                return this.columnCountField;
            }
            set {
                if ((this.columnCountField.Equals(value) != true)) {
                    this.columnCountField = value;
                    this.RaisePropertyChanged("columnCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Broobu.SweNet.Adapter.SweNet.ArrayOfString columnNames {
            get {
                return this.columnNamesField;
            }
            set {
                if ((object.ReferenceEquals(this.columnNamesField, value) != true)) {
                    this.columnNamesField = value;
                    this.RaisePropertyChanged("columnNames");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Broobu.SweNet.Adapter.SweNet.ArrayOfString columnTypes {
            get {
                return this.columnTypesField;
            }
            set {
                if ((object.ReferenceEquals(this.columnTypesField, value) != true)) {
                    this.columnTypesField = value;
                    this.RaisePropertyChanged("columnTypes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Broobu.SweNet.Adapter.SweNet.ArrayOfArrayOfAnyType data {
            get {
                return this.dataField;
            }
            set {
                if ((object.ReferenceEquals(this.dataField, value) != true)) {
                    this.dataField = value;
                    this.RaisePropertyChanged("data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime endDate {
            get {
                return this.endDateField;
            }
            set {
                if ((this.endDateField.Equals(value) != true)) {
                    this.endDateField = value;
                    this.RaisePropertyChanged("endDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int rowCount {
            get {
                return this.rowCountField;
            }
            set {
                if ((this.rowCountField.Equals(value) != true)) {
                    this.rowCountField = value;
                    this.RaisePropertyChanged("rowCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime startDate {
            get {
                return this.startDateField;
            }
            set {
                if ((this.startDateField.Equals(value) != true)) {
                    this.startDateField = value;
                    this.RaisePropertyChanged("startDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tableName {
            get {
                return this.tableNameField;
            }
            set {
                if ((object.ReferenceEquals(this.tableNameField, value) != true)) {
                    this.tableNameField = value;
                    this.RaisePropertyChanged("tableName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfArrayOfAnyType", Namespace="http://www.w3.org/2001/XMLSchema", ItemName="ArrayOfAnyType")]
    [System.SerializableAttribute()]
    public class ArrayOfArrayOfAnyType : System.Collections.Generic.List<Broobu.SweNet.Adapter.SweNet.ArrayOfAnyType> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfAnyType", Namespace="http://www.w3.org/2001/XMLSchema", ItemName="anyType")]
    [System.SerializableAttribute()]
    public class ArrayOfAnyType : System.Collections.Generic.List<object> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://esa-spaceweather.net/swenet/xfire-webservice", ConfigurationName="SweNet.ISwenetDataProviderPortType")]
    public interface ISwenetDataProviderPortType {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        void logout(string in0);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        Broobu.SweNet.Adapter.SweNet.ISwenetDataSet getData(string in0, string in1, Broobu.SweNet.Adapter.SweNet.ArrayOfString in2, System.DateTime in3, System.DateTime in4);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        Broobu.SweNet.Adapter.SweNet.ArrayOfString getColumnNames(string in0, string in1);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        Broobu.SweNet.Adapter.SweNet.ArrayOfString getTableNames(string in0);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        System.DateTime getLatestDate(string in0, string in1);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        Broobu.SweNet.Adapter.SweNet.ArrayOfString getColumnTypes(string in0, string in1);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string login(string in0, string in1);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISwenetDataProviderPortTypeChannel : Broobu.SweNet.Adapter.SweNet.ISwenetDataProviderPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SwenetDataProviderPortTypeClient : System.ServiceModel.ClientBase<Broobu.SweNet.Adapter.SweNet.ISwenetDataProviderPortType>, Broobu.SweNet.Adapter.SweNet.ISwenetDataProviderPortType {
        
        public SwenetDataProviderPortTypeClient() {
        }
        
        public SwenetDataProviderPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SwenetDataProviderPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SwenetDataProviderPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SwenetDataProviderPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void logout(string in0) {
            base.Channel.logout(in0);
        }
        
        public Broobu.SweNet.Adapter.SweNet.ISwenetDataSet getData(string in0, string in1, Broobu.SweNet.Adapter.SweNet.ArrayOfString in2, System.DateTime in3, System.DateTime in4) {
            return base.Channel.getData(in0, in1, in2, in3, in4);
        }
        
        public Broobu.SweNet.Adapter.SweNet.ArrayOfString getColumnNames(string in0, string in1) {
            return base.Channel.getColumnNames(in0, in1);
        }
        
        public Broobu.SweNet.Adapter.SweNet.ArrayOfString getTableNames(string in0) {
            return base.Channel.getTableNames(in0);
        }
        
        public System.DateTime getLatestDate(string in0, string in1) {
            return base.Channel.getLatestDate(in0, in1);
        }
        
        public Broobu.SweNet.Adapter.SweNet.ArrayOfString getColumnTypes(string in0, string in1) {
            return base.Channel.getColumnTypes(in0, in1);
        }
        
        public string login(string in0, string in1) {
            return base.Channel.login(in0, in1);
        }
    }
}
