// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 10.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Iris.Contract.Generation.Templates
{
    using System.Linq;
    using Iris.Contract.Generation.Domain;
    using System;
    
    
    #line 1 "J:\develop\Iris\IrisFx\Generation\Iris.Contract.Generation\Templates\ClassTemplate.tt"
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "10.0.0.0")]
    public partial class ClassTemplate : T4Toolbox.Template
    {
        public override string TransformText()
        {
            
            #line 4 "J:\develop\Iris\IrisFx\Generation\Iris.Contract.Generation\Templates\ClassTemplate.tt"
 foreach (var item in Class.UsedNamespaces) { 
            
            #line default
            #line hidden
            this.Write("using ");
            
            #line 4 "J:\develop\Iris\IrisFx\Generation\Iris.Contract.Generation\Templates\ClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 5 "J:\develop\Iris\IrisFx\Generation\Iris.Contract.Generation\Templates\ClassTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\nnamespace ");
            
            #line 7 "J:\develop\Iris\IrisFx\Generation\Iris.Contract.Generation\Templates\ClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Class.Namespace));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n");
            
            #line 9 "J:\develop\Iris\IrisFx\Generation\Iris.Contract.Generation\Templates\ClassTemplate.tt"
if(Class.Attributes!=null && Class.Attributes.Count()>0)
{
		foreach (AttributeDefinition attribute in Class.Attributes)
{
            
            #line default
            #line hidden
            this.Write("\t");
            
            #line 12 "J:\develop\Iris\IrisFx\Generation\Iris.Contract.Generation\Templates\ClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attribute));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 13 "J:\develop\Iris\IrisFx\Generation\Iris.Contract.Generation\Templates\ClassTemplate.tt"
 }
}
            
            #line default
            #line hidden
            this.Write("\t");
            
            #line 15 "J:\develop\Iris\IrisFx\Generation\Iris.Contract.Generation\Templates\ClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Class.Signature));
            
            #line default
            #line hidden
            this.Write("\r\n\t{\r\n");
            
            #line 17 "J:\develop\Iris\IrisFx\Generation\Iris.Contract.Generation\Templates\ClassTemplate.tt"
 if(Class.Constructors!=null && Class.Constructors.Count()>0) 
{
            
            #line default
            #line hidden
            this.Write("\t\t#region Constructors\r\n");
            
            #line 20 "J:\develop\Iris\IrisFx\Generation\Iris.Contract.Generation\Templates\ClassTemplate.tt"
foreach (ConstructorDefinition constructor in Class.Constructors)
{
	if(constructor.Attributes!=null && constructor.Attributes.Count()>0)
	{
		foreach (AttributeDefinition attribute in constructor.Attributes)
{
            
            #line default
            #line hidden
            this.Write("\t\t");
            
            #line 25 "J:\develop\Iris\IrisFx\Generation\Iris.Contract.Generation\Templates\ClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attribute));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 26 "J:\develop\Iris\IrisFx\Generation\Iris.Contract.Generation\Templates\ClassTemplate.tt"

}
	}
            
            #line default
            #line hidden
            this.Write("\t\t");
            
            #line 28 "J:\develop\Iris\IrisFx\Generation\Iris.Contract.Generation\Templates\ClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(constructor.Signature));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t{\r\n");
            
            #line 30 "J:\develop\Iris\IrisFx\Generation\Iris.Contract.Generation\Templates\ClassTemplate.tt"
 foreach (String line in System.Text.RegularExpressions.Regex.Split(constructor.Body, System.Environment.NewLine))
{
            
            #line default
            #line hidden
            this.Write("\t\t\t");
            
            #line 31 "J:\develop\Iris\IrisFx\Generation\Iris.Contract.Generation\Templates\ClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(line));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 32 "J:\develop\Iris\IrisFx\Generation\Iris.Contract.Generation\Templates\ClassTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t}\r\n");
            
            #line 34 "J:\develop\Iris\IrisFx\Generation\Iris.Contract.Generation\Templates\ClassTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("\t\t\t\r\n\t\t#endregion\t\t\r\n");
            
            #line 36 "J:\develop\Iris\IrisFx\Generation\Iris.Contract.Generation\Templates\ClassTemplate.tt"
}
            
            #line default
            #line hidden
            
            #line 37 "J:\develop\Iris\IrisFx\Generation\Iris.Contract.Generation\Templates\ClassTemplate.tt"
 if((Class.Fields!=null && Class.Fields.Count()>0)||(Class.Properties!=null && Class.Properties.Count()>0))
{ 
            
            #line default
            #line hidden
            this.Write("\t\t#region Fields\r\n");
            
            #line 40 "J:\develop\Iris\IrisFx\Generation\Iris.Contract.Generation\Templates\ClassTemplate.tt"
 foreach (FieldDefinition field in Class.Fields.Union(Class.Properties.Select(x=>(FieldDefinition)x))) 
{ 
            
            #line default
            #line hidden
            this.Write("\t\t");
            
            #line 41 "J:\develop\Iris\IrisFx\Generation\Iris.Contract.Generation\Templates\ClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Signature));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 42 "J:\develop\Iris\IrisFx\Generation\Iris.Contract.Generation\Templates\ClassTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t#endregion\r\n");
            
            #line 44 "J:\develop\Iris\IrisFx\Generation\Iris.Contract.Generation\Templates\ClassTemplate.tt"
}
if(Class.Properties!=null && Class.Properties.Count()>0)
{ 
            
            #line default
            #line hidden
            this.Write("\t\t#region Properties\r\n");
            
            #line 48 "J:\develop\Iris\IrisFx\Generation\Iris.Contract.Generation\Templates\ClassTemplate.tt"
 foreach (PropertyDefinition property in Class.Properties) 
{
	if(property.Attributes!=null && property.Attributes.Count()>0)
	{
		foreach (AttributeDefinition attribute in property.Attributes)
{
            
            #line default
            #line hidden
            this.Write("\t\t");
            
            #line 53 "J:\develop\Iris\IrisFx\Generation\Iris.Contract.Generation\Templates\ClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attribute));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 54 "J:\develop\Iris\IrisFx\Generation\Iris.Contract.Generation\Templates\ClassTemplate.tt"
 }
} 
            
            #line default
            #line hidden
            this.Write("\t\t");
            
            #line 55 "J:\develop\Iris\IrisFx\Generation\Iris.Contract.Generation\Templates\ClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Signature));
            
            #line default
            #line hidden
            
            #line 55 "J:\develop\Iris\IrisFx\Generation\Iris.Contract.Generation\Templates\ClassTemplate.tt"
 if(!System.String.IsNullOrWhiteSpace(property.GetBody)&& !System.String.IsNullOrWhiteSpace(property.GetBody))
{ 
            
            #line default
            #line hidden
            this.Write("\r\n\t\t{\r\n\t\t\tget\r\n\t\t\t{\r\n");
            
            #line 61 "J:\develop\Iris\IrisFx\Generation\Iris.Contract.Generation\Templates\ClassTemplate.tt"
 foreach (String line in System.Text.RegularExpressions.Regex.Split(property.GetBody, System.Environment.NewLine))
{
            
            #line default
            #line hidden
            this.Write("\t\t\t\t");
            
            #line 62 "J:\develop\Iris\IrisFx\Generation\Iris.Contract.Generation\Templates\ClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(line));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 63 "J:\develop\Iris\IrisFx\Generation\Iris.Contract.Generation\Templates\ClassTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t\t}\r\n\t\t\tset\r\n\t\t\t{\r\n");
            
            #line 67 "J:\develop\Iris\IrisFx\Generation\Iris.Contract.Generation\Templates\ClassTemplate.tt"
 foreach (String line in System.Text.RegularExpressions.Regex.Split(property.SetBody, System.Environment.NewLine))
{
            
            #line default
            #line hidden
            this.Write("\t\t\t\t");
            
            #line 68 "J:\develop\Iris\IrisFx\Generation\Iris.Contract.Generation\Templates\ClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(line));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 69 "J:\develop\Iris\IrisFx\Generation\Iris.Contract.Generation\Templates\ClassTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t\t}\r\n\t\t}\r\n");
            
            #line 72 "J:\develop\Iris\IrisFx\Generation\Iris.Contract.Generation\Templates\ClassTemplate.tt"
 } else if(System.String.IsNullOrWhiteSpace(property.GetBody)&& System.String.IsNullOrWhiteSpace(property.GetBody))
{ 
            
            #line default
            #line hidden
            this.Write(" { get; set; }\r\n");
            
            #line 74 "J:\develop\Iris\IrisFx\Generation\Iris.Contract.Generation\Templates\ClassTemplate.tt"
 } else if(!System.String.IsNullOrWhiteSpace(property.GetBody))
{ 
            
            #line default
            #line hidden
            this.Write("\r\n\t\t{\r\n\t\t\tget\r\n\t\t\t{\r\n");
            
            #line 80 "J:\develop\Iris\IrisFx\Generation\Iris.Contract.Generation\Templates\ClassTemplate.tt"
 foreach (String line in System.Text.RegularExpressions.Regex.Split(property.GetBody, System.Environment.NewLine))
{
            
            #line default
            #line hidden
            this.Write("\t\t\t\t");
            
            #line 81 "J:\develop\Iris\IrisFx\Generation\Iris.Contract.Generation\Templates\ClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(line));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 82 "J:\develop\Iris\IrisFx\Generation\Iris.Contract.Generation\Templates\ClassTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t\t}\r\n\t\t}\r\n");
            
            #line 85 "J:\develop\Iris\IrisFx\Generation\Iris.Contract.Generation\Templates\ClassTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 86 "J:\develop\Iris\IrisFx\Generation\Iris.Contract.Generation\Templates\ClassTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t#endregion\r\n");
            
            #line 88 "J:\develop\Iris\IrisFx\Generation\Iris.Contract.Generation\Templates\ClassTemplate.tt"
}
            
            #line default
            #line hidden
            
            #line 89 "J:\develop\Iris\IrisFx\Generation\Iris.Contract.Generation\Templates\ClassTemplate.tt"
 if(Class.Events!=null && Class.Events.Count()>0) 
{
            
            #line default
            #line hidden
            this.Write("\t\t#region Events\r\n");
            
            #line 92 "J:\develop\Iris\IrisFx\Generation\Iris.Contract.Generation\Templates\ClassTemplate.tt"
foreach (EventDefinition item in Class.Events)
{
            
            #line default
            #line hidden
            this.Write("\t\t");
            
            #line 93 "J:\develop\Iris\IrisFx\Generation\Iris.Contract.Generation\Templates\ClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Signature));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 94 "J:\develop\Iris\IrisFx\Generation\Iris.Contract.Generation\Templates\ClassTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("\t\t\r\n\t\t#endregion\t\t\r\n");
            
            #line 96 "J:\develop\Iris\IrisFx\Generation\Iris.Contract.Generation\Templates\ClassTemplate.tt"
}
            
            #line default
            #line hidden
            
            #line 97 "J:\develop\Iris\IrisFx\Generation\Iris.Contract.Generation\Templates\ClassTemplate.tt"
 if(Class.Methods!=null && Class.Methods.Count()>0) 
{
            
            #line default
            #line hidden
            this.Write("\t\t#region Methods\r\n");
            
            #line 100 "J:\develop\Iris\IrisFx\Generation\Iris.Contract.Generation\Templates\ClassTemplate.tt"
foreach (MethodDefinition method in Class.Methods)
{
	if(method.Attributes!=null && method.Attributes.Count()>0)
	{
		foreach (AttributeDefinition attribute in method.Attributes)
{
            
            #line default
            #line hidden
            this.Write("\t\t");
            
            #line 105 "J:\develop\Iris\IrisFx\Generation\Iris.Contract.Generation\Templates\ClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attribute));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 106 "J:\develop\Iris\IrisFx\Generation\Iris.Contract.Generation\Templates\ClassTemplate.tt"
 }
} 
            
            #line default
            #line hidden
            this.Write("\t\t");
            
            #line 107 "J:\develop\Iris\IrisFx\Generation\Iris.Contract.Generation\Templates\ClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.Signature));
            
            #line default
            #line hidden
            
            #line 107 "J:\develop\Iris\IrisFx\Generation\Iris.Contract.Generation\Templates\ClassTemplate.tt"
 if(method.IsPartial && System.String.IsNullOrWhiteSpace(method.Body)) { 
            
            #line default
            #line hidden
            this.Write(";");
            
            #line 107 "J:\develop\Iris\IrisFx\Generation\Iris.Contract.Generation\Templates\ClassTemplate.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write("\r\n\t\t{\r\n");
            
            #line 110 "J:\develop\Iris\IrisFx\Generation\Iris.Contract.Generation\Templates\ClassTemplate.tt"
 foreach (String line in System.Text.RegularExpressions.Regex.Split(method.Body, System.Environment.NewLine))
{
            
            #line default
            #line hidden
            this.Write("\t\t\t");
            
            #line 111 "J:\develop\Iris\IrisFx\Generation\Iris.Contract.Generation\Templates\ClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(line));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 112 "J:\develop\Iris\IrisFx\Generation\Iris.Contract.Generation\Templates\ClassTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t}\r\n");
            
            #line 114 "J:\develop\Iris\IrisFx\Generation\Iris.Contract.Generation\Templates\ClassTemplate.tt"
}
}
            
            #line default
            #line hidden
            this.Write("\t\t\t\r\n\t\t#endregion\t\t\r\n");
            
            #line 117 "J:\develop\Iris\IrisFx\Generation\Iris.Contract.Generation\Templates\ClassTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("\t}\r\n}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
