// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 10.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Iris.Contract.Generation.Templates
{
    using System;
    
    
    #line 1 "J:\develop\Iris\IrisFx\Generation\Iris.Contract.Generation\Templates\ErrorTemplate.tt"
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "10.0.0.0")]
    public partial class ErrorTemplate : T4Toolbox.Template
    {
        public override string TransformText()
        {
            
            #line 3 "J:\develop\Iris\IrisFx\Generation\Iris.Contract.Generation\Templates\ErrorTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetExceptionInformation()));
            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
