// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 10.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Iris.Contract.Generation.Templates
{
    using System.Linq;
    using Iris.Contract.Generation.Domain;
    using System;
    
    
    #line 1 "J:\develop\Iris\IrisFx\Generation\Iris.Contract.Generation\Templates\InterfaceTemplate.tt"
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "10.0.0.0")]
    public partial class InterfaceTemplate : T4Toolbox.Template
    {
        public override string TransformText()
        {
            this.Write(@"//	========================================================================================
//	INFO: This file is generated from a T4 template.
//  !!!	Any changes made manually will be lost next time this file is regenerated !!!
//	========================================================================================
");
            
            #line 8 "J:\develop\Iris\IrisFx\Generation\Iris.Contract.Generation\Templates\InterfaceTemplate.tt"
 foreach (String item in Interface.UsedNamespaces) { 
            
            #line default
            #line hidden
            this.Write("using ");
            
            #line 8 "J:\develop\Iris\IrisFx\Generation\Iris.Contract.Generation\Templates\InterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 9 "J:\develop\Iris\IrisFx\Generation\Iris.Contract.Generation\Templates\InterfaceTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\nnamespace ");
            
            #line 11 "J:\develop\Iris\IrisFx\Generation\Iris.Contract.Generation\Templates\InterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Interface.Namespace));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n");
            
            #line 13 "J:\develop\Iris\IrisFx\Generation\Iris.Contract.Generation\Templates\InterfaceTemplate.tt"
if(Interface.Attributes!=null && Interface.Attributes.Count()>0)
{
		foreach (AttributeDefinition attribute in Interface.Attributes)
{
            
            #line default
            #line hidden
            this.Write("\t");
            
            #line 16 "J:\develop\Iris\IrisFx\Generation\Iris.Contract.Generation\Templates\InterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attribute));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 17 "J:\develop\Iris\IrisFx\Generation\Iris.Contract.Generation\Templates\InterfaceTemplate.tt"
 }
}
            
            #line default
            #line hidden
            this.Write("  \t");
            
            #line 19 "J:\develop\Iris\IrisFx\Generation\Iris.Contract.Generation\Templates\InterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Interface.Signature));
            
            #line default
            #line hidden
            this.Write("\r\n  \t{\r\n");
            
            #line 21 "J:\develop\Iris\IrisFx\Generation\Iris.Contract.Generation\Templates\InterfaceTemplate.tt"
 if(Interface.Events!=null && Interface.Events.Count()>0)
{
            
            #line default
            #line hidden
            this.Write("\t\t#region Events\r\n");
            
            #line 23 "J:\develop\Iris\IrisFx\Generation\Iris.Contract.Generation\Templates\InterfaceTemplate.tt"
foreach (EventDefinition eventInfo in Interface.Events)
{
	if(eventInfo.Attributes!=null && eventInfo.Attributes.Count()>0)
	{
		foreach (AttributeDefinition attribute in eventInfo.Attributes)
{
            
            #line default
            #line hidden
            this.Write("\t\t");
            
            #line 28 "J:\develop\Iris\IrisFx\Generation\Iris.Contract.Generation\Templates\InterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attribute));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 29 "J:\develop\Iris\IrisFx\Generation\Iris.Contract.Generation\Templates\InterfaceTemplate.tt"
 }
} 
            
            #line default
            #line hidden
            this.Write("\t\t");
            
            #line 30 "J:\develop\Iris\IrisFx\Generation\Iris.Contract.Generation\Templates\InterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(String.Format("{0};", eventInfo.Signature)));
            
            #line default
            #line hidden
            this.Write("\r\n\r\n");
            
            #line 32 "J:\develop\Iris\IrisFx\Generation\Iris.Contract.Generation\Templates\InterfaceTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("\t\t#endregion\r\n");
            
            #line 34 "J:\develop\Iris\IrisFx\Generation\Iris.Contract.Generation\Templates\InterfaceTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 35 "J:\develop\Iris\IrisFx\Generation\Iris.Contract.Generation\Templates\InterfaceTemplate.tt"
 if(Interface.Methods!=null && Interface.Methods.Count()>0)
{
            
            #line default
            #line hidden
            this.Write("\t\t#region Methods\r\n");
            
            #line 37 "J:\develop\Iris\IrisFx\Generation\Iris.Contract.Generation\Templates\InterfaceTemplate.tt"
foreach (MethodDefinition method in Interface.Methods)
{
	if(method.Attributes!=null && method.Attributes.Count()>0)
	{
		foreach (AttributeDefinition attribute in method.Attributes)
{
            
            #line default
            #line hidden
            this.Write("\t\t");
            
            #line 42 "J:\develop\Iris\IrisFx\Generation\Iris.Contract.Generation\Templates\InterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attribute));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 43 "J:\develop\Iris\IrisFx\Generation\Iris.Contract.Generation\Templates\InterfaceTemplate.tt"
 }
} 
            
            #line default
            #line hidden
            this.Write("\t\t");
            
            #line 44 "J:\develop\Iris\IrisFx\Generation\Iris.Contract.Generation\Templates\InterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(String.Format("{0};", method.Signature)));
            
            #line default
            #line hidden
            this.Write("\r\n\r\n");
            
            #line 46 "J:\develop\Iris\IrisFx\Generation\Iris.Contract.Generation\Templates\InterfaceTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("\t\t#endregion\r\n");
            
            #line 48 "J:\develop\Iris\IrisFx\Generation\Iris.Contract.Generation\Templates\InterfaceTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n\t}\r\n}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
